# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='reply_tweet_id',
            field=models.IntegerField(null=True),
        ),
    ]
